// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow that provides AI-powered suggestions on how to improve a user's profile description.
 *
 * - suggestProfileImprovements - A function that handles the profile improvement suggestion process.
 * - SuggestProfileImprovementsInput - The input type for the suggestProfileImprovements function.
 * - SuggestProfileImprovementsOutput - The return type for the suggestProfileImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProfileImprovementsInputSchema = z.object({
  profileDescription: z
    .string()
    .describe('The user provided description of their profile.'),
});

export type SuggestProfileImprovementsInput = z.infer<
  typeof SuggestProfileImprovementsInputSchema
>;

const SuggestProfileImprovementsOutputSchema = z.object({
  improvedDescription: z
    .string()
    .describe('AI-powered suggestions to improve the profile description.'),
});

export type SuggestProfileImprovementsOutput = z.infer<
  typeof SuggestProfileImprovementsOutputSchema
>;

export async function suggestProfileImprovements(
  input: SuggestProfileImprovementsInput
): Promise<SuggestProfileImprovementsOutput> {
  return suggestProfileImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProfileImprovementsPrompt',
  input: {schema: SuggestProfileImprovementsInputSchema},
  output: {schema: SuggestProfileImprovementsOutputSchema},
  prompt: `You are an AI-powered profile improvement assistant. Your task is to analyze a user's profile description and provide suggestions on how to improve it to attract more matches.

User Profile Description: {{{profileDescription}}}

Provide suggestions to improve the profile description. Focus on making the description more engaging, highlighting key qualities, and suggesting specific examples or anecdotes to add.`,
});

const suggestProfileImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestProfileImprovementsFlow',
    inputSchema: SuggestProfileImprovementsInputSchema,
    outputSchema: SuggestProfileImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
