-- Create the messages table to store chat messages between users
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    sender_id uuid NOT NULL,
    recipient_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_read boolean NOT NULL DEFAULT false,
    CONSTRAINT messages_pkey PRIMARY KEY (id),
    CONSTRAINT messages_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
    CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
    CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.messages IS 'Stores individual chat messages for a given match.';
COMMENT ON COLUMN public.messages.id IS 'Unique identifier for the message.';
COMMENT ON COLUMN public.messages.match_id IS 'Foreign key to the matches table.';
COMMENT ON COLUMN public.messages.sender_id IS 'The user who sent the message.';
COMMENT ON COLUMN public.messages.recipient_id IS 'The user who received the message.';
COMMENT ON COLUMN public.messages.content IS 'The text content of the message.';
COMMENT ON COLUMN public.messages.created_at IS 'When the message was sent.';
COMMENT ON COLUMN public.messages.is_read IS 'Whether the recipient has read the message.';


-- 1. Enable RLS on the new table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 2. Create a policy that allows users to see messages that they've sent or received
CREATE POLICY "Allow users to view their own messages"
ON public.messages
FOR SELECT
USING (
  auth.uid() = sender_id OR auth.uid() = recipient_id
);

-- 3. Create a policy that allows users to send messages in matches they are part of
CREATE POLICY "Allow users to insert messages in their matches"
ON public.messages
FOR INSERT
WITH CHECK (
  auth.uid() = sender_id AND
  EXISTS (
    SELECT 1 FROM public.matches
    WHERE
      id = match_id AND
      (user1_id = sender_id AND user2_id = recipient_id) OR
      (user1_id = recipient_id AND user2_id = sender_id)
  )
);
